export const CountriesActionTypes={


    SHOW_COUNTRIES_START: 'SHOW_COUNTRIES_START',
    SHOW_COUNTRIES_SUCCESS: 'SHOW_COUNTRIES_SUCCESS',
    SHOW_COUNTRIES_FAILURE: 'SHOW_COUNTRIES_FAILURE',





}
