export const ContinentActionTypes={


    SHOW_CONTINENT_START: 'SHOW_CONTINENT_START',
    SHOW_CONTINENT_SUCCESS: 'SHOW_CONTINENT_SUCCESS',
    SHOW_CONTINENT_FAILURE: 'SHOW_CONTINENT_FAILURE',





}
